pip install Jinja2
pip install MarkupSafe
pip install PySocks
pip install allure-pytest
pip install allure-python-commons
pip install attrs
pip install certifi
pip install cffi
pip install charset-normalizer
pip install colorama
pip install et_xmlfile
pip install execnet
pip install h11
pip install idna
pip install iniconfig
pip install openpyxl
pip install outcome
pip install packaging
pip install pip
pip install pluggy
pip install pycparser
pip install pytest
pip install pytest-html
pip install pytest-metadata
pip install pytest-xdist
pip install python-dotenv
pip install requests
pip install selenium
pip install sniffio
pip install sortedcontainers
pip install trio
pip install trio-websocket
pip install typing_extensions
pip install urllib3
pip install webdriver-manager
pip install websocket-client
pip install wsproto